version: "3.9"
services:
  cassandra:
    build: './cassandra'
    container_name: 'cassandra'
    ports: 
      - 9042
    healthcheck:
      test:
        - 'CMD-SHELL'
        - "cqlsh --execute 'SELECT now() from system.local'"
      interval: '3s'
      timeout: '2s'
      retries: 10

